[tool.poetry]
name = "wode"
version = "0.1.0"
description = ""
authors = ["Hannes"]
readme = "README.md"
packages = [{ include = "wode" }]

[tool.poetry.dependencies]
python = "^3.10"
koda = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
flake8 = "^5.0.4"
Flake8-pyproject = "^1.1.0.post0"
isort = "^5.10.1"
pydocstyle = "^6.1.1"
pyright = "^1.1.271"
pytest = "^7.1.3"
ssort = "^0.11.6"

[tool.isort]
profile = "black"

[tool.flake8]
ignore = ["E501", "E203", "W503"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
