name: Run Pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        env:
          # Don't fail when running on main branch
          SKIP: no-commit-to-branch
